.github/ISSUE_TEMPLATE/community-request-.md

Add an issue template for community proposed feature requests

Update issue templates

---

PRINCIPLES.md

sorry, couldn't help myself.
Capitalize Open Source, inline with the trademark and AWS guidance.

Capitalize Open Source

---

README.md
preview-programs/eks-windows-preview/README.md
preview-programs/eks-windows-preview/amazon-eks-cfn-quickstart-windows.yaml
preview-programs/eks-windows-preview/amazon-eks-windows-nodegroup.yaml
preview-programs/eks-windows-preview/aws-auth-cm-windows.yaml
preview-programs/eks-windows-preview/eks-clusteraddons-quickstart-windows.yaml
preview-programs/eks-windows-preview/vpc-admission-webhook-deployment.yaml
preview-programs/eks-windows-preview/webhook-create-signed-cert.sh
preview-programs/eks-windows-preview/webhook-patch-ca-bundle.sh
preview-programs/eks-windows-preview/windows-server-IIS.yaml

Added readme and files to support the public preview of Windows Nodes on Amazon EKS

windows preview

---

preview-programs/eks-windows-preview/README.md

Update URL for Linux AMI in ReadMe for EKS Windows Preview.

Update URL for Linux AMI

---

preview-programs/eks-windows-preview/README.md

*Description of changes:* minor README things I saw while going through it

Fix urls, spacing, & typo

---

preview-programs/eks-windows-preview/README.md

Signed-off-by: Vinothkumar Siddharth <sidvin@amazon.com>
Update AMIs

Update Windows Preview AMIs

---

preview-programs/firelens/README.md
preview-programs/firelens/cloudwatch_task_definition.json
preview-programs/firelens/firehose_task_definition.json
preview-programs/firelens/forward_task_definition.json

TODO: Actually register and test those example task definitions. [DONE]

Documentation for FireLens Preview

---

preview-programs/firelens/README.md

Remove console support note from Preview README

---

preview-programs/firelens/cloudwatch_task_definition.json
preview-programs/firelens/firehose_task_definition.json
preview-programs/firelens/forward_task_definition.json

Add Task Roles, Logging on the FireLens container, and replace memory with memoryReservation for the FireLens examples

Improve FireLens preview examples

---

preview-programs/eks-windows-preview/README.md

Deprecate Windows preview

---

preview-programs/eks-ec2-a1-preview/README.md

https://github.com/aws/containers-roadmap/issues/264#issuecomment-504164409
A1 assets are populated outside of us-west-2 region. Adjusted preview instructions.

Updated A1 preview availability

---

preview-programs/firelens/README.md

Note that FireLens is now GA

---

preview-programs/firelens/README.md

Add Bahrain ECR image

---

.github/ISSUE_TEMPLATE/community-request-.md
.github/PULL_REQUEST_TEMPLATE.md

Add community note to issue/PR templates

---

preview-programs/eks-ec2-a1-preview/README.md

Updated instructions to use new account ID and updated template instructions for the new CloudFormation template.

Updated instructions to use new account ID and updated template.

---

preview-programs/eks-ec2-a1-preview/README.md
preview-programs/eks-ec2-a1-preview/amazon-eks-arm-nodegroup.yaml

Removed reference to NodeImageID parameter, updated GitHub copy of NodeGroup template.

---

preview-programs/eks-ec2-a1-preview/README.md
preview-programs/eks-ec2-a1-preview/dns-arm-1.13.yaml
preview-programs/eks-ec2-a1-preview/dns-arm-1.14.yaml
preview-programs/eks-ec2-a1-preview/kube-proxy-arm-1.13.yaml
preview-programs/eks-ec2-a1-preview/kube-proxy-arm-1.14.yaml

*Issue #, if available:* N/A
Adding kube-proxy and coreDNS manifest files for EKS ARM instances

Adding kube-proxy and coreDNS files for EKS ARM instances

---

preview-programs/eks-ec2-a1-preview/aws-k8s-cni-arm64.yaml
preview-programs/eks-ec2-a1-preview/cni-metrics-helper-arm64.yaml
preview-programs/eks-ec2-a1-preview/dns-arm-1.14.yaml
preview-programs/eks-ec2-a1-preview/kube-proxy-arm-1.13.yaml
preview-programs/eks-ec2-a1-preview/kube-proxy-arm-1.14.yaml

Updating cni/dns/kube-proxy addon binary version to latest in manifest

---

README.md

*Issue #, if available:* N/A
*Description of changes:* Fixing [broken link](https://github.com/aws/containers-roadmap/blob/master/master/preview-programs/ecs-multipletg-service)
@tabern

fixing preview link in README

---

.github/ISSUE_TEMPLATE/community-request-.md
.github/ISSUE_TEMPLATE/eks-arm-preview-feedback.md
.github/PULL_REQUEST_TEMPLATE.md

N/A
Added security note to issue template. 

Added security note to PR/Issue templates

---

README.md

Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
<!--
*Description of changes:* Update the README.md to reflect the link of the GA announcement of EKS on ARM / Graviton

Update EKS on ARM link in Readme

---

README.md

Add link to AWS CDK Roadmap

---

preview-programs/zz_archive/ecs-multipletg-service/README.md

Typo in preview-programs/zz_archive/ecs-multipletg-service/README.md
avaliable => available

fix(docs): Corrected typo in project documentation
